name = "mosaic-paid-check"
main = "index.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/5 * * * *"]

[vars]
# --- Airtable ---
AIRTABLE_BASE_ID = "appw4WQJbbR1AP5ZD"
AIRTABLE_ORDERS_TABLE_NAME = "Orders"

# Field names (если в Airtable EXACT такие же — можно вообще не указывать)
AIRTABLE_TRACKING_FIELD = "Tracking Number"
AIRTABLE_SHIPPED_FIELD = "Shipped Email Sent"
AIRTABLE_CUSTOMER_EMAIL_FIELD = "Customer Email"
AIRTABLE_CUSTOMER_NAME_FIELD = "Customer Name"
AIRTABLE_ORDER_ID_FIELD = "Order ID"
AIRTABLE_ORDER_ID_FIELDI = "OrderCode"
AIRTABLE_ORDER_STATUS_FIELD = "Order Status"
AIRTABLE_PAID_SENT_FIELD = "Paid Email Sent"
AIRTABLE_CUSTOMER_EMAIL_FIELD = "Customer Email"
AIRTABLE_CUSTOMER_NAME_FIELD = "Customer Name"
AIRTABLE_ORDER_CODE_FIELD = "OrderCode"
AIRTABLE_AMOUNT_FIELD = "Amount Total"
AIRTABLE_CURRENCY_FIELD = "Currency"

# --- Email ---
STORE_NAME = "Mosaic Pins"
MAIL_FROM = "support@mosaicpins.space"
MAIL_REPLY_TO = "mosaicpinsspace@gmail.com"
# optional:
MAIL_BCC = "mosaicpinsspace@gmail.com"